agent:
  providers:
    research: gemini
project:
  key: TOO
  name: Monoco Toolkit
  spike_repos:
    MinerU: https://github.com/opendatalab/MinerU
    SWE-agent: https://github.com/SWE-agent/SWE-agent
    SWE-bench: https://github.com/SWE-bench/SWE-bench
    Typedown: https://github.com/IndenScale/Typedown
    agent-client-protocol: https://github.com/agentclientprotocol/agent-client-protocol
    agentskills: https://github.com/agentskills/agentskills
    claude-agent-sdk-python: https://github.com/anthropics/claude-agent-sdk-python
    claude-code: https://github.com/anthropics/claude-code
    gemini-cli: https://github.com/google-gemini/gemini-cli
    kimi-agent-sdk: https://github.com/MoonshotAI/kimi-agent-sdk
    monoco-toolkit: https://github.com/IndenScale/monoco-toolkit
    qwen-code: https://github.com/QwenLM/qwen-code
    ralph: https://github.com/snarktank/ralph
    skills: https://github.com/anthropics/skills
    vibe-kanban: https://github.com/BloopAI/vibe-kanban
