agent:
  providers:
    research: gemini
project:
  key: TOO
  name: Monoco Toolkit
  spike_repos:
    agentskills: https://github.com/agentskills/agentskills
    gemini-cli: https://github.com/google-gemini/gemini-cli
    qwen-code: https://github.com/QwenLM/qwen-code
    skills: https://github.com/anthropics/skills
    vibe-kanban: https://github.com/BloopAI/vibe-kanban
